# 18.02.2021: temporarily disabled as labeler keeps removing the labels
# Add 'Run nested' label to either any change on nested lib or nested test
#Run nested:
#- any: ['tests/lib/nested.sh', 'tests/nested/**/*']
