name: Unit Tests
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  # TODO: run static checks before we run unit tests
  # TODO: run spread tests, in a matrix, after we run unit tests
  # TODO: port static checks as well
  unit-tests:
    runs-on: ubuntu-latest
    env:
      GOPATH: ${{ github.workspace }}
      GO111MODULE: off
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        # NOTE: checkout the code in a fixed location, even for forks, as this
        # is relevant for go's import system.
        path: ./src/github.com/snapcore/snapd
    - name: Cache Debian dependencies
      id: cache-deb-downloads
      uses: actions/cache@v1
      with:
        path: /var/cache/apt
        key: var-cache-apt-{{ hashFiles('**/debian/control') }}
    - name: Download Debian dependencies
      if: steps.cache-deb-downloads.outputs.cache-hit != 'true'
      run: |
          sudo apt clean
          sudo apt update
          sudo apt build-dep -d -y ${{ github.workspace }}/src/github.com/snapcore/snapd
    # Work around caching files owned by root https://github.com/actions/cache/issues/133
    - name: Make /var/cache/apt owned by current user
      run: sudo chown -R $(id -u) /var/cache/apt
    - name: Install Debian dependencies
      run: sudo apt build-dep -y ${{ github.workspace }}/src/github.com/snapcore/snapd
    - name: Set up go 1.9
      uses: actions/setup-go@v1
      with:
        go-version: 1.9
    - name: Install govendor
      run: go get -u github.com/kardianos/govendor
    - name: Cache Go dependencies
      id: cache-go-govendor
      uses: actions/cache@v1
      with:
        path: ${{ github.workspace }}/.cache/govendor
        key: go-govendor-{{ hashFiles('**/vendor.json') }}
    - name: Get Go dependencies
      run: |
          cd ${{ github.workspace }}/src/github.com/snapcore/snapd
          ${{ github.workspace }}/bin/govendor sync
    - name: Build C
      run: |
          cd ${{ github.workspace }}/src/github.com/snapcore/snapd/cmd/
          ./autogen.sh
          make -j2
    - name: Build Go
      run: go build github.com/snapcore/snapd/...
    - name: Test C
      run: |
          cd ${{ github.workspace }}/src/github.com/snapcore/snapd/cmd/
          make check
    - name: Test Go
      run: go test github.com/snapcore/snapd/...
