name: Unit Tests
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  # TODO: run static checks before we run unit tests
  # TODO: run spread tests, in a matrix, after we run unit tests
  # TODO: port static checks as well
  unit-tests:
    runs-on: ubuntu-latest
    env:
      GOPATH: ${{ github.workspace }}
      GO111MODULE: off
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        # NOTE: checkout the code in a fixed location, even for forks, as this
        # is relevant for go's import system.
        path: ./src/github.com/snapcore/snapd
    - name: Set up go 1.9
      uses: actions/setup-go@v1
      with:
        go-version: 1.9
    - name: Install govendor
      run: go get -u github.com/kardianos/govendor
    - name: Cache Debian dependencies
      id: cache-deb-downloads
      uses: actions/cache@v1
      with:
        path: /tmp/debian-packages/
        key: dpkg-debian-{{ hashFiles('**/debian/control') }}
    - name: Download Debian dependencies
      if: steps.cache-deb-downloads.outputs.cache-hit != 'true'
      run: |
          sudo apt clean
          sudo apt update
          sudo apt build-dep -d -y ${{ github.workspace }}/src/github.com/snapcore/snapd
          mkdir -p /tmp/debian-packages/
          cp /var/cache/apt/archives/*.deb /tmp/debian-packages
    - name: Install Debian dependencies
      run: |
          cd /tmp/debian-packages
          sudo apt install --no-install-recommends -y ./*.deb
    - name: Get Go dependencies
      run: |
          cd ${{ github.workspace }}/src/github.com/snapcore/snapd
          ${{ github.workspace }}/bin/govendor sync
    - name: Cache go's .cache directory (used by govendor)
      id: cache-go-govendor
      uses: actions/cache@v1
      with:
        path: ${{ github.workspace }}/.cache/govendor
        key: go-govendor-{{ hashFiles('**/vendor.json') }}
    - name: Build C
      run: |
          cd ${{ github.workspace }}/src/github.com/snapcore/snapd/cmd/
          ./autogen.sh
          make -j2
    - name: Build Go
      run: go build github.com/snapcore/snapd/...
    - name: Test C
      run: |
          cd ${{ github.workspace }}/src/github.com/snapcore/snapd/cmd/
          make check
    - name: Test Go
      run: go test github.com/snapcore/snapd/...
