name: Quick Go unit tests
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  linux:
    runs-on: ubuntu-latest
    env:
      GOPATH: ${{ github.workspace }}
      GO111MODULE: off
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        path: ./src/github.com/${{ github.repository }}
    - name: Cache go pkg directory
      id: cache-go-pkg
      uses: actions/cache@v1
      with:
        path: ${{ github.workspace }}/pkg
        key: ${{ runner.os }}-go-pkg
    - name: Cache go vendor packages
      id: cache-go-vendor
      uses: actions/cache@v1
      with:
        path: ${{ github.workspace }}/src/github.com/${{ github.repository }}/vendor
        key: ${{ runner.os }}-go-vendor
    - name: Set up go 1.9
      uses: actions/setup-go@v1
      with:
        go-version: 1.9
      id: go  # XXX: what is this for?
    - name: Install govendor
      run: go get -u github.com/kardianos/govendor
    # This dominates the duration of the test. Can we get a smaller set that is
    # enough to build embedded C parts?
    - name: Get C dependencies
      run: sudo apt-get build-dep -y ./src/github.com/${{ github.repository }}
    - name: Get Go dependencies
      run: |
          cd ${{ github.workspace }}/src/github.com/${{ github.repository }}
          ${{ github.workspace }}/bin/govendor sync
    - name: Build
      run: go build github.com/snapcore/snapd/...
    - name: Test
      run: go build github.com/snapcore/snapd/...
